=== lermns/Curso22-23/1DAM-DOC's/LenguajeDeMarcas/UT5.Almacenamiento de la informacion/Recursos/clientes/cliente.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="cliente">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombreCompleto"/>
        <xs:element ref="telefonos"/>
        <xs:element name="fechaNac" type="xs:date"/>
        <xs:element ref="formacion"/>
        <xs:element ref="direccion"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombreCompleto">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="apellido1" type="xs:string"/>
        <xs:element name="apellido2" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="telefonos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tel" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="formacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulacion" type="xs:string" maxOccurs="unbounded"/>
        <xs:element ref="idioma" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="idioma">
    <xs:complexType mixed="true">
      <xs:attribute name="nivel" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="direccion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TipoVia" type="xs:string"/>
        <xs:element name="nombreVia" type="xs:string"/>
        <xs:element name="numeroVia" type="xs:string"/>
        <xs:element name="piso" type="xs:string" minOccurs="0"/>
        <xs:element name="puerta" type="xs:string" minOccurs="0"/>
        <xs:element name="cp" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lermns/Curso22-23/1DAM-DOC's/LenguajeDeMarcas/UT5.Almacenamiento de la informacion/Recursos/clientes/425500.xml
<?xml version="1.0" encoding="UTF-8"?>
<cliente xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cliente.xsd"
  id="425500">
<nombreCompleto>
  <nombre>Alberto</nombre>
  <apellido1>Rosati</apellido1>
  <apellido2>Juriel</apellido2>
</nombreCompleto>
<telefonos>
  <tel>65890011</tel>
  <tel>65268855</tel>
  <tel>916988236</tel>
</telefonos>
  <fechaNac>2000-11-27</fechaNac>
<formacion>
<titulacion>Graduado Bellas Artes</titulacion>
<titulacion>Muralista</titulacion>
<idioma nivel="B1">Inglés</idioma>
<idioma nivel="B2">Alemán</idioma>
</formacion>
<direccion>
<TipoVia>Plaza</TipoVia>
<nombreVia>Indiano</nombreVia>
<numeroVia>12</numeroVia>
<piso>5</piso>
<puerta>C</puerta>
<cp>28055</cp>
</direccion>
</cliente>

=== lermns/Curso22-23/1DAM-DOC's/LenguajeDeMarcas/UT5.Almacenamiento de la informacion/Recursos/clientes/225562.xml
<?xml version="1.0" encoding="UTF-8"?>
<cliente xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cliente.xsd"
  id="225562">
<nombreCompleto>
  <nombre>Ana</nombre>
  <apellido1>Ruiz</apellido1>
  <apellido2>Lara</apellido2>
</nombreCompleto>
<telefonos>
  <tel>65289963</tel>
  <tel>61589233</tel>
</telefonos>
  <fechaNac>1996-03-21</fechaNac>
<formacion>
<titulacion>Técnico Superior Administración de Sistemas Informáticos</titulacion>
<titulacion>CCNA nivel 1</titulacion>
<idioma nivel="B2">Inglés</idioma>
<idioma nivel="B1">Alemán</idioma>
</formacion>
<direccion>
<TipoVia>Calle</TipoVia>
<nombreVia>Albastros</nombreVia>
<numeroVia>6</numeroVia>
<piso>5</piso>
<puerta>B</puerta>
<cp>28822</cp>
</direccion>
</cliente>

=== lermns/Curso22-23/1DAM-DOC's/LenguajeDeMarcas/UT5.Almacenamiento de la informacion/Recursos/clientes/225102.xml
<?xml version="1.0" encoding="UTF-8"?>
<cliente xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cliente.xsd"
  id="225102">
<nombreCompleto>
  <nombre>Juana</nombre>
  <apellido1>Mateo</apellido1>
  <apellido2>Quina</apellido2>
</nombreCompleto>
<telefonos>
  <tel>65201147</tel>
</telefonos>
  <fechaNac>1998-01-08</fechaNac>
<formacion>
<titulacion>Técnico Superior Administración de Sistemas Informáticos</titulacion>
<titulacion>CCNA nivel 1</titulacion>
<idioma nivel="B2">Inglés</idioma>
</formacion>
<direccion>
<TipoVia>Calle</TipoVia>
<nombreVia>Altamira</nombreVia>
<numeroVia>64</numeroVia>
<cp>28843</cp>
</direccion>
</cliente>
