=== lermns/Curso22-23/1DAM-DOC's/LenguajeDeMarcas/UT4.Conversion y adaptacion de documentos XML/Recursos/inventario/inventario/inventario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="inventario">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="equipo" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="año" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="equipo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="peso"/>
        <xs:element name="tipo" type="xs:string"/>
        <xs:element ref="lugar"/>
      </xs:sequence>
      <xs:attribute name="codigo" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="peso">
    <xs:complexType mixed="true">
      <xs:attribute name="unidad" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="lugar">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sala" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="edificio" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lermns/Curso22-23/1DAM-DOC's/LenguajeDeMarcas/UT4.Conversion y adaptacion de documentos XML/Recursos/inventario/inventario/inventario.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="inventario.xsl"?>
<inventario año="2022" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="inventario.xsd">
    <equipo codigo="P1">
        <peso unidad="kg">10</peso>
        <tipo>Router</tipo>
        <lugar edificio="B">
            <sala>101</sala>
        </lugar>
    </equipo>
    <equipo codigo="P2">
        <peso unidad="g">500</peso>
        <tipo>Switch</tipo>
        <lugar edificio="A">
            <sala>206</sala>
        </lugar>
    </equipo>
    <equipo codigo="P3">
        <peso unidad="g">350</peso>
        <tipo>Switch</tipo>
        <lugar edificio="A">
            <sala>207</sala>
        </lugar>
    </equipo>
    <equipo codigo="P4">
        <peso unidad="g">300</peso>
        <tipo>Switch</tipo>
        <lugar edificio="A">
         <sala>210</sala>
        </lugar>
    </equipo>
</inventario>
